# Generated by Django 4.0.3 on 2023-01-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_appointment_vin_alter_appointment_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled',
        ),
        migrations.AddField(
            model_name='appointment',
            name='in_progress',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='VIN',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service_rest.technician'),
        ),
    ]
