# Generated by Django 4.0.3 on 2023-01-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_rename_name_technician_technician_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='technician',
            new_name='technician_name',
        ),
    ]
