# Generated by Django 4.0.3 on 2023-01-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_rename_technician_appointment_technician_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='VIN',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
