# Generated by Django 4.0.3 on 2023-01-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_alter_appointment_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='technician_name',
            new_name='technician',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='technician_name',
            new_name='name',
        ),
    ]
