# Generated by Django 4.0.3 on 2023-01-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0013_alter_appointment_in_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date_time']},
        ),
    ]
