# Generated by Django 4.0.3 on 2023-01-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0014_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
    ]
