# Generated by Django 4.0.3 on 2023-01-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0016_alter_appointment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='in_progress',
        ),
    ]
